version: "3"

services:
  devmark:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./config:/app/config
    command: ["./devmark", "serve"]
