// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package repository

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Bookmark struct {
	ID          int64              `db:"id" json:"id"`
	Link        *string            `db:"link" json:"link"`
	CategoryID  *int64             `db:"category_id" json:"category_id"`
	WorkspaceID *int64             `db:"workspace_id" json:"workspace_id"`
	Summary     *string            `db:"summary" json:"summary"`
	CreatedAt   pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	UserID      *int64             `db:"user_id" json:"user_id"`
	Title       *string            `db:"title" json:"title"`
	IsRead      *bool              `db:"is_read" json:"is_read"`
}

type BookmarkComment struct {
	ID          int64                 `db:"id" json:"id"`
	Link        *string               `db:"link" json:"link"`
	CategoryID  *int64                `db:"category_id" json:"category_id"`
	WorkspaceID *int64                `db:"workspace_id" json:"workspace_id"`
	Summary     *string               `db:"summary" json:"summary"`
	CreatedAt   pgtype.Timestamptz    `db:"created_at" json:"created_at"`
	UpdatedAt   pgtype.Timestamptz    `db:"updated_at" json:"updated_at"`
	UserID      *int64                `db:"user_id" json:"user_id"`
	Title       *string               `db:"title" json:"title"`
	Comments    []*BookmarkCommentRow `db:"comments" json:"comments"`
}

type Category struct {
	ID        int64              `db:"id" json:"id"`
	Name      *string            `db:"name" json:"name"`
	CreatedAt pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type Comment struct {
	ID             int64              `db:"id" json:"id"`
	BookmarkID     *int64             `db:"bookmark_id" json:"bookmark_id"`
	UserID         *int64             `db:"user_id" json:"user_id"`
	CommentContext *string            `db:"comment_context" json:"comment_context"`
	CreatedAt      pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type DeviceInfo struct {
	ID                int64              `db:"id" json:"id"`
	UserID            *int64             `db:"user_id" json:"user_id"`
	RegistrationToken *string            `db:"registration_token" json:"registration_token"`
	CreatedAt         pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type InviteCode struct {
	ID          int64              `db:"id" json:"id"`
	WorkspaceID *int32             `db:"workspace_id" json:"workspace_id"`
	Code        *string            `db:"code" json:"code"`
	ExpiredAt   pgtype.Timestamptz `db:"expired_at" json:"expired_at"`
	CreatedAt   pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type NotificationHistory struct {
	ID                int64              `db:"id" json:"id"`
	UserID            *int64             `db:"user_id" json:"user_id"`
	NotificationTitle *string            `db:"notification_title" json:"notification_title"`
	IsRead            *bool              `db:"is_read" json:"is_read"`
	CreatedAt         pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	BookmarkID        *int64             `db:"bookmark_id" json:"bookmark_id"`
}

type RecommendLink struct {
	ID          int64              `db:"id" json:"id"`
	WorkspaceID *int64             `db:"workspace_id" json:"workspace_id"`
	Link        *string            `db:"link" json:"link"`
	CreatedAt   pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	CategoryID  *int64             `db:"category_id" json:"category_id"`
	Title       *string            `db:"title" json:"title"`
}

type RefreshToken struct {
	ID        int64              `db:"id" json:"id"`
	Token     *string            `db:"token" json:"token"`
	UserID    *int32             `db:"user_id" json:"user_id"`
	CreatedAt pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type TopWorkspaceCategory struct {
	WorkspaceID    *int64          `db:"workspace_id" json:"workspace_id"`
	CategoryID     *int64          `db:"category_id" json:"category_id"`
	BookmarkCount  int64           `db:"bookmark_count" json:"bookmark_count"`
	RecommendLinks []RecommendLink `db:"recommend_links" json:"recommend_links"`
}

type UnreadBookmark struct {
	UserID      *int64       `db:"user_id" json:"user_id"`
	WorkspaceID *int64       `db:"workspace_id" json:"workspace_id"`
	Bookmarks   []Bookmark   `db:"bookmarks" json:"bookmarks"`
	DeviceInfos []DeviceInfo `db:"device_infos" json:"device_infos"`
}

type UnreadNotification struct {
	UserID          int64                  `db:"user_id" json:"user_id"`
	Username        *string                `db:"username" json:"username"`
	Notifications   []*NotificationHistory `db:"notifications" json:"notifications"`
	BookmarkID      int64                  `db:"bookmark_id" json:"bookmark_id"`
	BookmarkLink    *string                `db:"bookmark_link" json:"bookmark_link"`
	BookmarkSummary *string                `db:"bookmark_summary" json:"bookmark_summary"`
	BookmarkTitle   *string                `db:"bookmark_title" json:"bookmark_title"`
}

type User struct {
	ID           int64              `db:"id" json:"id"`
	Username     *string            `db:"username" json:"username"`
	Provider     *string            `db:"provider" json:"provider"`
	RefreshToken *int32             `db:"refresh_token" json:"refresh_token"`
	CreatedAt    pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type UserWorkspaceView struct {
	ID         *int64       `db:"id" json:"id"`
	Workspaces []*Workspace `db:"workspaces" json:"workspaces"`
}

type Workspace struct {
	ID            int64              `db:"id" json:"id"`
	Name          *string            `db:"name" json:"name"`
	Description   *string            `db:"description" json:"description"`
	CreatedAt     pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	BookmarkCount *int32             `db:"bookmark_count" json:"bookmark_count"`
	UserCount     *int32             `db:"user_count" json:"user_count"`
}

type WorkspaceCategory struct {
	WorkspaceID int64 `db:"workspace_id" json:"workspace_id"`
	CategoryID  int64 `db:"category_id" json:"category_id"`
}

type WorkspaceCategoryList struct {
	ID            int64              `db:"id" json:"id"`
	Name          *string            `db:"name" json:"name"`
	Description   *string            `db:"description" json:"description"`
	CreatedAt     pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	BookmarkCount *int32             `db:"bookmark_count" json:"bookmark_count"`
	UserCount     *int32             `db:"user_count" json:"user_count"`
	Categories    []*Category        `db:"categories" json:"categories"`
}

type WorkspaceCode struct {
	ID          int64              `db:"id" json:"id"`
	WorkspaceID *int64             `db:"workspace_id" json:"workspace_id"`
	Code        *string            `db:"code" json:"code"`
	CreatedAt   pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	UserID      *int64             `db:"user_id" json:"user_id"`
}

type WorkspaceUser struct {
	WorkspaceID int64 `db:"workspace_id" json:"workspace_id"`
	UserID      int64 `db:"user_id" json:"user_id"`
}

type WorkspaceUserBookmarkCount struct {
	WorkspaceID       int64               `db:"workspace_id" json:"workspace_id"`
	UserBookmarkCount []UserBookmarkCount `db:"user_bookmark_count" json:"user_bookmark_count"`
}

type WorkspaceUserCategory struct {
	ID            int64              `db:"id" json:"id"`
	Name          *string            `db:"name" json:"name"`
	Description   *string            `db:"description" json:"description"`
	CreatedAt     pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	BookmarkCount *int32             `db:"bookmark_count" json:"bookmark_count"`
	UserCount     *int32             `db:"user_count" json:"user_count"`
	Categories    []*Category        `db:"categories" json:"categories"`
	Users         []*FindUserByIdRow `db:"users" json:"users"`
}
