// Code generated by mockery v2.38.0. DO NOT EDIT.

package mocks

import (
	responses "github.com/MJU-Capstone-6/devmark-backend/internal/responses"
	mock "github.com/stretchr/testify/mock"
)

// IAuthService is an autogenerated mock type for the IAuthService type
type IAuthService struct {
	mock.Mock
}

// KakaoSignUp provides a mock function with given fields: _a0, _a1, _a2
func (_m *IAuthService) KakaoSignUp(_a0 string, _a1 string, _a2 string) (*responses.GetKakaoInfoResponse, error) {
	ret := _m.Called(_a0, _a1, _a2)

	if len(ret) == 0 {
		panic("no return value specified for KakaoSignUp")
	}

	var r0 *responses.GetKakaoInfoResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(string, string, string) (*responses.GetKakaoInfoResponse, error)); ok {
		return rf(_a0, _a1, _a2)
	}
	if rf, ok := ret.Get(0).(func(string, string, string) *responses.GetKakaoInfoResponse); ok {
		r0 = rf(_a0, _a1, _a2)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*responses.GetKakaoInfoResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(string, string, string) error); ok {
		r1 = rf(_a0, _a1, _a2)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewIAuthService creates a new instance of IAuthService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIAuthService(t interface {
	mock.TestingT
	Cleanup(func())
}) *IAuthService {
	mock := &IAuthService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
