// Code generated by mockery v2.38.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// INotificationService is an autogenerated mock type for the INotificationService type
type INotificationService struct {
	mock.Mock
}

// SendUnreadBookmarkNotification provides a mock function with given fields:
func (_m *INotificationService) SendUnreadBookmarkNotification() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for SendUnreadBookmarkNotification")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewINotificationService creates a new instance of INotificationService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewINotificationService(t interface {
	mock.TestingT
	Cleanup(func())
}) *INotificationService {
	mock := &INotificationService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
