// Code generated by mockery v2.38.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// IRecommendService is an autogenerated mock type for the IRecommendService type
type IRecommendService struct {
	mock.Mock
}

// NewIRecommendService creates a new instance of IRecommendService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIRecommendService(t interface {
	mock.TestingT
	Cleanup(func())
}) *IRecommendService {
	mock := &IRecommendService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
