basePath: /
definitions:
  auth.GetKakaoInfoResponse:
    properties:
      access_key:
        type: string
    type: object
  customerror.CustomError:
    properties:
      data: {}
      error_code:
        type: string
      msg:
        type: string
      status_code:
        type: integer
    type: object
host: localhost
info:
  contact:
    email: sjlee990129@gmail.com
    name: MilkyMilky0116
    url: https://milkymilky0116.github.io
  description: Bookmark service with automatic classification.
  title: Devmark API
  version: "1.0"
paths:
  /auth/kakao:
    get:
      consumes:
      - application/json
      description: Retrive user info from kakao oauth. If user exists in our service,
        then return access token.
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/auth.GetKakaoInfoResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/customerror.CustomError'
      summary: Retrive user info from kakao oauth
      tags:
      - users
swagger: "2.0"
